'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property DefaultLineIndex() As Integer
        Get
            Return CType(Me("DefaultLineIndex"),Integer)
        End Get
        Set
            Me("DefaultLineIndex") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("All Sites")>  _
    Public Property DefaultSite() As String
        Get
            Return CType(Me("DefaultSite"),String)
        End Get
        Set
            Me("DefaultSite") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("All Sectors")>  _
    Public Property DefaultBU() As String
        Get
            Return CType(Me("DefaultBU"),String)
        End Get
        Set
            Me("DefaultBU") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property areDatesSaved() As Boolean
        Get
            Return CType(Me("areDatesSaved"),Boolean)
        End Get
        Set
            Me("areDatesSaved") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("14")>  _
    Public Property defaultMappingLevel() As Integer
        Get
            Return CType(Me("defaultMappingLevel"),Integer)
        End Get
        Set
            Me("defaultMappingLevel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
    Public Property maxMinCOgap() As Integer
        Get
            Return CType(Me("maxMinCOgap"),Integer)
        End Get
        Set
            Me("maxMinCOgap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property inControl_useRule1() As Boolean
        Get
            Return CType(Me("inControl_useRule1"),Boolean)
        End Get
        Set
            Me("inControl_useRule1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property inControl_useRule2() As Boolean
        Get
            Return CType(Me("inControl_useRule2"),Boolean)
        End Get
        Set
            Me("inControl_useRule2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property inControl_useRule3() As Boolean
        Get
            Return CType(Me("inControl_useRule3"),Boolean)
        End Get
        Set
            Me("inControl_useRule3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property inControl_useRule4() As Boolean
        Get
            Return CType(Me("inControl_useRule4"),Boolean)
        End Get
        Set
            Me("inControl_useRule4") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("no")>  _
    Public Property CSV_ExportPath() As String
        Get
            Return CType(Me("CSV_ExportPath"),String)
        End Get
        Set
            Me("CSV_ExportPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LanguageActive() As Integer
        Get
            Return CType(Me("LanguageActive"),Integer)
        End Get
        Set
            Me("LanguageActive") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property populateDTteamsFromPROD() As Boolean
        Get
            Return CType(Me("populateDTteamsFromPROD"),Boolean)
        End Get
        Set
            Me("populateDTteamsFromPROD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
    Public Property maxuptimecutoff() As Double
        Get
            Return CType(Me("maxuptimecutoff"),Double)
        End Get
        Set
            Me("maxuptimecutoff") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property displaySAPnames() As Boolean
        Get
            Return CType(Me("displaySAPnames"),Boolean)
        End Get
        Set
            Me("displaySAPnames") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property inControl_useRule5() As Boolean
        Get
            Return CType(Me("inControl_useRule5"),Boolean)
        End Get
        Set
            Me("inControl_useRule5") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property inControl_useRule6() As String
        Get
            Return CType(Me("inControl_useRule6"),String)
        End Get
        Set
            Me("inControl_useRule6") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property AdvancedSettings_MultiConstraintAnalysisMode() As Integer
        Get
            Return CType(Me("AdvancedSettings_MultiConstraintAnalysisMode"),Integer)
        End Get
        Set
            Me("AdvancedSettings_MultiConstraintAnalysisMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("14")>  _
    Public Property defaultDownTimeField() As Integer
        Get
            Return CType(Me("defaultDownTimeField"),Integer)
        End Get
        Set
            Me("defaultDownTimeField") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property AdvancedSettings_isAvailabilityMode() As Boolean
        Get
            Return CType(Me("AdvancedSettings_isAvailabilityMode"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_isAvailabilityMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property defaultDownTimeField_Secondary() As Integer
        Get
            Return CType(Me("defaultDownTimeField_Secondary"),Integer)
        End Get
        Set
            Me("defaultDownTimeField_Secondary") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property WantstoSetDefaultLine() As Boolean
        Get
            Return CType(Me("WantstoSetDefaultLine"),Boolean)
        End Get
        Set
            Me("WantstoSetDefaultLine") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_isTargetsEnabled() As Boolean
        Get
            Return CType(Me("AdvancedSettings_isTargetsEnabled"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_isTargetsEnabled") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_isPasswordCorrect() As Boolean
        Get
            Return CType(Me("AdvancedSettings_isPasswordCorrect"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_isPasswordCorrect") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
    Public Property Data_UptimeCutoff() As Long
        Get
            Return CType(Me("Data_UptimeCutoff"),Long)
        End Get
        Set
            Me("Data_UptimeCutoff") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
    Public Property Data_DowntimeCutoff() As Long
        Get
            Return CType(Me("Data_DowntimeCutoff"),Long)
        End Get
        Set
            Me("Data_DowntimeCutoff") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_UseNotes() As Boolean
        Get
            Return CType(Me("AdvancedSettings_UseNotes"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_UseNotes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_UseSimulation() As Boolean
        Get
            Return CType(Me("AdvancedSettings_UseSimulation"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_UseSimulation") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PDT_maxMinutesBetweenEvents() As Integer
        Get
            Return CType(Me("PDT_maxMinutesBetweenEvents"),Integer)
        End Get
        Set
            Me("PDT_maxMinutesBetweenEvents") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property DefaultLineName() As String
        Get
            Return CType(Me("DefaultLineName"),String)
        End Get
        Set
            Me("DefaultLineName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("GBO")>  _
    Public Property DefaultSiteAcronym() As String
        Get
            Return CType(Me("DefaultSiteAcronym"),String)
        End Get
        Set
            Me("DefaultSiteAcronym") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Skin Care")>  _
    Public Property DefaultModuleName() As String
        Get
            Return CType(Me("DefaultModuleName"),String)
        End Get
        Set
            Me("DefaultModuleName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property LastEndDate() As Date
        Get
            Return CType(Me("LastEndDate"),Date)
        End Get
        Set
            Me("LastEndDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property LastStartDate() As Date
        Get
            Return CType(Me("LastStartDate"),Date)
        End Get
        Set
            Me("LastStartDate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_PlaySnake() As Boolean
        Get
            Return CType(Me("AdvancedSettings_PlaySnake"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_PlaySnake") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
    Public Property AdvancedSettings_DTcutoff() As Double
        Get
            Return CType(Me("AdvancedSettings_DTcutoff"),Double)
        End Get
        Set
            Me("AdvancedSettings_DTcutoff") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowUpdateNews() As Boolean
        Get
            Return CType(Me("ShowUpdateNews"),Boolean)
        End Get
        Set
            Me("ShowUpdateNews") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
    Public Property AdvancedSettings_UTcutoff() As String
        Get
            Return CType(Me("AdvancedSettings_UTcutoff"),String)
        End Get
        Set
            Me("AdvancedSettings_UTcutoff") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("x")>  _
    Public Property MultilineSelection() As String
        Get
            Return CType(Me("MultilineSelection"),String)
        End Get
        Set
            Me("MultilineSelection") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MultilineRememberSelection() As Boolean
        Get
            Return CType(Me("MultilineRememberSelection"),Boolean)
        End Get
        Set
            Me("MultilineRememberSelection") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property DefaultStartTimeMinutes() As Integer
        Get
            Return CType(Me("DefaultStartTimeMinutes"),Integer)
        End Get
        Set
            Me("DefaultStartTimeMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property DefaultEndTimeMinutes() As Integer
        Get
            Return CType(Me("DefaultEndTimeMinutes"),Integer)
        End Get
        Set
            Me("DefaultEndTimeMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property AdvancedSettings_ProdUseMinutes() As Boolean
        Get
            Return CType(Me("AdvancedSettings_ProdUseMinutes"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_ProdUseMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property AdvancedSettings_AvailUseMinutes() As Boolean
        Get
            Return CType(Me("AdvancedSettings_AvailUseMinutes"),Boolean)
        End Get
        Set
            Me("AdvancedSettings_AvailUseMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property DefaultStartTimeHour() As Integer
        Get
            Return CType(Me("DefaultStartTimeHour"),Integer)
        End Get
        Set
            Me("DefaultStartTimeHour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property DefaultEndTimeHour() As Integer
        Get
            Return CType(Me("DefaultEndTimeHour"),Integer)
        End Get
        Set
            Me("DefaultEndTimeHour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EnableTimeSpanExclusion() As Boolean
        Get
            Return CType(Me("EnableTimeSpanExclusion"),Boolean)
        End Get
        Set
            Me("EnableTimeSpanExclusion") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Exclude_StartHour() As Integer
        Get
            Return CType(Me("Exclude_StartHour"),Integer)
        End Get
        Set
            Me("Exclude_StartHour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("23")>  _
    Public Property Exclude_EndHour() As Integer
        Get
            Return CType(Me("Exclude_EndHour"),Integer)
        End Get
        Set
            Me("Exclude_EndHour") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Exclude_StartMinutes() As Integer
        Get
            Return CType(Me("Exclude_StartMinutes"),Integer)
        End Get
        Set
            Me("Exclude_StartMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Exclude_EndMinutes() As Integer
        Get
            Return CType(Me("Exclude_EndMinutes"),Integer)
        End Get
        Set
            Me("Exclude_EndMinutes") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PostMap_Enable() As Boolean
        Get
            Return CType(Me("PostMap_Enable"),Boolean)
        End Get
        Set
            Me("PostMap_Enable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property PostMap_Field1() As Integer
        Get
            Return CType(Me("PostMap_Field1"),Integer)
        End Get
        Set
            Me("PostMap_Field1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property PostMap_Field2() As Integer
        Get
            Return CType(Me("PostMap_Field2"),Integer)
        End Get
        Set
            Me("PostMap_Field2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property PostMap_Field3() As Integer
        Get
            Return CType(Me("PostMap_Field3"),Integer)
        End Get
        Set
            Me("PostMap_Field3") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DigitalFactory.MySettings
            Get
                Return Global.DigitalFactory.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
